name: .NET Build & Test

on:
  push:
    branches:
      - main
      - developer
      - 'feature/*'
  pull_request:
    branches:
      - main
      - developer
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH:
          CalculatorSolution/CalculatorSolution.sln
      UNIT_TEST_PROJECT:
          CalculatorSolution/CalculatorTests/CalculatorSolution.sln

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Debug -show files
        run: |
          echo "Current directory:" && pwd
          echo "List top-level files and floders:" && ls -la
          echo "List CalculatorSolution floders:" && ls -la CalculatorSolution || true

      - name: Restore dependencies
        run: dotnet restore "$SOLUTION_PATH"

      - name: Build solution
        run: dotnet build "$SOLUTION_PATH" --configuration Release --no-restore


        #------------------Unit Test--------------------
      - name: Run unit tests
        run: dotnet test "UNIT_TEST_PROJECT" --configuration Release --no-build --verbosity normal

      
        
