name: .NET Build & Test

on:
  push:
    branches:
      - main
      - developer
      - 'feature/*'
  pull_request:
    branches:
      - main
      - developer
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Debug -show files
        run: |
          echo "Current directory:" && pwd
          echo "List top-level files and floders:" && ls -la
          echo "List CalculatorSolution floders:" && ls -la CalculatorSolution || true
          echo "Find any .sln files:" && find . -name ".sln" -maxdepth 3

      - name: Restore dependencies
        working-directory: CalculatorSolution
        run: dotnet restore CalculatorSolution.sln

      - name: Build solution
        working-directory: CalculatorSolution
        run: dotnet build CalculatorSolution.sln --configuration Release --no-restore


        #------------------Unit Test--------------------
      - name: Run unit tests
        working-directory: CalculatorSolution
        run: dotnet test CalculatorSolution/CalculatorTests.csproj --configuration Release --no-build --verbosity normal

      
        
